### ISSUE TITLE
Annex A.5: Does track_ID uniqueness hold for CMAF ISO BMFF Tracks?

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/CMAF-Byte-Stream#15]
The track is:
- A CTA-608 closed caption service: the string “cc” concatenated with the decimal representation of the channel_number
-  A CTA-708 closed caption service: the string “sn” concatenated with the decimal representation of the service_number field in the ‘Caption Channel Service Block’
- Otherwise, the decimal representation of the track_ID of a TrackHeaderBox (tkhd) in a TrackBox (trak).

*Editor's Note: Assuming true, but does track_ID uniqueness hold for CMAF ISOBMFF tracks?*

**Comment by technogeek00** [comment]
My last call notes had the statement that track_ID uniqueness is not guaranteed with CMAF, but this was going to be checked further. Did anyone have time to follow-up?

**Comment by sdp198** [comment]
CMAF requires track_IDs to be the same across all Tracks in a switching set, but does not place any requirement outside of that.  So two different switching sets can (and often do) use the same track_ID.  In my experience almost all tracks use track_ID=1, since the packager is only putting one track in each file it has no reason to do anything other than start at 1.

**Comment by technogeek00** [comment]
@sdp198 thanks for your comment, this aligns with my own experience and expectations otherwise the independent creation of tracks needs a centralized orchestrator which may be counter to workflow operations.

From the perspective of setting ids on Video/Audio/Text tracks it might be best to require all ids to either be:
- uniquely generated at track creation time by the track management engine
- supplied by the logical player as part of the track creation

**Comment by haudiobe** [comment]
AHG Call 2020/10/19:
addressed in revised draft. Unless any comments are received, the issue will be closed by the next meeting.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
