### ISSUE TITLE
Initialization Segment: Inband Parameters

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/CMAF-Byte-Stream#4]
John Simmons:
As discussed in our conference call, inband parameters including SPS and PPS parameter sets are ALLOWED in CMAF and therefore are REQUIRED for a User Agent to assert it supports CMAF content. So, for CMAF this must change from a SHOULD to a MUST.

**Comment by haudiobe** [comment]
This is already addressed in the draft, so accepted.

**Comment by ihofmann-iis** [comment]
I think the concept has never been specified "codec independent", i.e. AVC/HEVC/MPEG-H Audio have it in their respective ISOBMFF bindings, but part 12 doesn't talk about the concept. Is this good enough for a "MUST" at this point? I agree with the requirement, I'm just worried about the formality.

**Comment by haudiobe** [comment]
One way to solve this, is to remove the should statement. In this way, any sample entry needs to be mandatorily supported. Informative text may be sufficient then.

**Comment by haudiobe** [comment]
Agreed - needs implementation

**Comment by haudiobe** [comment]
Added an update to requirement: https://docs.google.com/document/d/1WNK2JTY6wW1qGqi7pFpsJvF-rowj2ssmI_NxjNQrh7I/edit#bookmark=id.o1cqhnn9ivan
Added a Note: https://docs.google.com/document/d/1WNK2JTY6wW1qGqi7pFpsJvF-rowj2ssmI_NxjNQrh7I/edit#bookmark=id.iuux1fucf49x

**Comment by haudiobe** [comment]
(CTA WAVE 2020/03/24): Online updates done - please check

**Comment by poolec** [comment]
I think this needs to be clearer, and be more than a note because it's a difference compared to the ISO BMFF byte stream format and it's a requirement that inband parameter sets be supported for CMAF compatibility.

This is widely supported in browsers and should not be an issue, despite the ISO BMFF byte stream format only recommending support.

How about the following, to mirror the paragraph in the ISO BMFF format spec:

"
The user agent MUST support codec configurations stored out-of-band in the sample entry, and for those CMAF profiles that allow codec configurations stored inband in the samples themselves, the user agent MUST support codec configurations stored inband.
"

**Comment by johnsim** [comment]
I think the proposed edit by @poolec makes sense.

**Comment by haudiobe** [comment]
(2020/04/14 CTA WAVE): We added the suggestion by @poolec, but we leave the discussion open to check the details in ISO/IEC 14496-15 on what "support" for these values means and secondly, whether this behaviour can be generalized to either ISO BMFF or at least CMAF behaviour to avoid this underspecified language.

**Comment by haudiobe** [comment]
(2020/05/05 CTA WAVE) Proposed to update with a reference to CMAF on the exact format requirements and processing behaviour: https://1drv.ms/w/s!AiNJEPgowJnWgpQgyV-LNLGRiYiWqA?e=YaVJBy

**Comment by haudiobe** [comment]
Small updates done inline.
